name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

permissions:
    contents: read

jobs:
  test:
    runs-on: ubuntu-latest  # Use GitHub-hosted Linux runner

    env:
      LOG_LEVEL: INFO
      GITHUB_USERNAME: fake_username
      GITHUB_PAT: fake_personal_access_tokne
      OPENAI_API_KEY: fake-openapi-key
      ANTHROPIC_API_KEY: fake-anthropicapi-key
      OLLAMA_BASE_URL: fake-ollama_base_url

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.12'  # Match your local version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --require-hashes -r requirements-dev.txt
          python -m pip install --require-hashes -r requirements.txt
          

      # Step 4: Run pytest (will use pytest.ini automatically)
      - name: Run pytest
        run: |
          pytest
